#!/usr/bin/with-contenv bash
ROOT_DIR=/app

# Replace env vars in HTML files
echo "Replacing env constants in HTML"
for file in $ROOT_DIR/index.html;
do
  echo "Processing $file ...";

  sed -i 's|VUE_APP_THEME|'${THEME}'|g' $file 
  sed -i 's|VUE_APP_LOGO|'${LOGO}'|g' $file
  # sed -i 's|VUE_APP_VERSION|'${VERSION}'|g' $file

done
